FROM golang:1.18-alpine3.14 AS builder


COPY ./ /github.com/Raimbekst/footballService

WORKDIR /github.com/Raimbekst/footballService

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o ./.bin/app ./cmd/app/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=0 /github.com/Raimbekst/footballService/.bin/app .
COPY --from=0 /github.com/Raimbekst/footballService/internal/config/ ./config
COPY --from=0 /github.com/Raimbekst/footballService/templates ./templates/

CMD ["./app"]