http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

db:
  username: "postgres"
  host: "localhost"
  port: "5438"
  dbname: "postgres"
  sslmode: "disable"


auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days

redis:
  redis_db: 0