ErrPasswordNotFound     = "пользователь с данным паролем не существует"
ErrNumberNotFound       = "пользователь с данным номером не существует"
ErrNumberEntered        = "неправильный номер телефона"
ErrWrongCodeEntered     = "введен неправильный код"
ErrActivateNumber       = "активировать номер телефона"
ErrPhoneType            = "номер телефона недействителен"
ErrNumberFormat         = "номер телефона недействителен. Формат номера: +770744422244"
ErrUserExist            = "пользователь с данным номером уже существует или активирован"
ErrUserActivated        = "пользователь с данным номером уже активирован"
ErrUserRegistered       = "пользователь с данным номером уже зарегистрирован"
ErrWrongPasswordEntered = "введен неверный текущий пароль"
ErrUserDoesntExist      = "пользователь не существует"
required    = "необходим {{.what}}"
emailL       = "{{.what}} должна быть действительной"
default     = "{{.what}} недействительен(на)"
password = "пароль"
phone    = "номер телефона"
email    = "электронная почта"