ErrPasswordNotFound  = "user with given password doesn't exists"
ErrNumberNotFound    = "user with given number does not exist"
ErrNumberEntered     = "wrong phone number"
ErrWrongCodeEntered  = "wrong code entered"
ErrActivateNumber    = "activate phone number"
ErrPhoneType         = "phone number is invalid"
ErrNumberFormat      = "phone number is invalid.Number format: +770744422244"
ErrUserExist         = "user with given number already exist or activated"
ErrUserActivated     = "user with given number already activated"
ErrUserRegistered    = "user with given number already registered"
ErrWrongPasswordEntered = "wrong current password entered"
ErrUserDoesntExist      =  "user doesn't exists"
required    = "The {{.what}} is required"
emailL       = "The {{.what}} must be valid"
default     = "The {{.what}} is invalid"
password = "password"
phone    = "phone number"
email    = "email"